### PR TITLE
Use title from the project-manager package if it's available

### PR DESCRIPTION
**Pull request by danielbrodin**
Hey,

I have a couple of users that want to see the title they use in the project-manager package in the window title, so I have implemented this through replacing the projectName var with the title from the project-manager if the package is available

### CODE REVIEW

**Comment by m1ga** [comment]
:+1:

**Comment by jolsen71** [comment]
@postcasio, please accept pull request #10. I was looking for this exact functionality and found @danielbrodin's PR and tested it. It appears to work perfectly both with a project in the project manager list and a normal atom project not in the project manager list.

**Comment by sigzegv** [comment]
I was looking to this exact functionnality, please accept request

**Comment by langpavel** [comment]
Hi @postcasio Any progress?

**Comment by proteo** [comment]
I'd like to see it accepted to!

**Comment by jolsen71** [comment]
@postcasio Thank you for this plugin and I assume you have a lot going on. If at all possible, please accept this PR and bump and push a new version. I'd like to avoid creating a fork of this project and adding it to Atom's repository, but starting to consider it. 

Thank you again for all for your work on this project.

**Comment by pixilz** [comment]
@danielbrodin There hasn't been a response on anything for a while so I created a fork of this project that I will be updating and maintaining, if you would like to add this pull request there that would be great! 
You can find the atom package here: https://atom.io/packages/custom-window-title

https://github.com/pixilz/custom-window-title

If @postcasio starts updating this package again I can merge the whole project over.

**Pull request closed without merging**
